### ISSUE TITLE
默认主题希望能添加一个分享的按钮

### ISSUE THREAD

**Issue by xus66666** [halo-dev/theme-earth#101]
<img width="849" alt="image" src="https://github.com/halo-dev/theme-earth/assets/68573596/f08de761-c9dd-4049-84bd-5a5c39d23dbd">
类似这个位置..或者文章末尾,总之.希望能添加一个默认按钮

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/theme-earth/pull/118 中支持。

/close
