### ISSUE TITLE
bug: 布局文章列表单条模式显示内容不全

### ISSUE THREAD

**Issue by yankooo** [halo-dev/theme-earth#102]
<img width="1144" alt="image" src="https://github.com/halo-dev/theme-earth/assets/31951382/108f8e0b-fad1-47aa-979a-d9ea3cbb5f10">

类似这样单条模式，为什么右边总是空出一大部分空白，应该是适配没做好？还是特性就是这样？

**Comment by ruibaby** [comment]
应该是因为文章没有设置封面图导致的，可以优化以下。

/kind improvement
/good-first-issue

**Comment by chenkuicn** [comment]
后续优化文章单条布局时，可以选择封面图的位置，居左或者居右

**Comment by ruibaby** [comment]
这个问题应该已经在 https://github.com/halo-dev/theme-earth/releases/tag/v1.9.0 中优化。

/close
