### ISSUE TITLE
媒体查询失效

### ISSUE THREAD

**Issue by Dacong-wu** [halo-dev/theme-earth#106]
为什么 grid grid-cols-6 sm:grid-cols-2 lg:grid-cols-6 不会生效？
<img width="991" alt="image" src="https://github.com/halo-dev/theme-earth/assets/62319007/3e80d306-b58b-4f84-8b33-e4e10d673e61">

**Comment by Dacong-wu** [comment]
profile.html文件下

**Comment by Dacong-wu** [comment]
profile.html文件下

**Comment by ruibaby** [comment]
不生效指的是？

我看截图似乎不是 `grid grid-cols-6 sm:grid-cols-2 lg:grid-cols-6`，所以是指修改代码之后没有更新模板吗？ 开发环境需要禁用模板引擎缓存，可以查看：https://docs.halo.run/developer-guide/theme/prepare#%E6%90%AD%E5%BB%BA%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83

如果是指编写的 TailwindCSS 代码没有生效，可以 `pnpm build` 之后再看看。

/kind support

**Comment by Dacong-wu** [comment]
是缓存的问题，谢谢
