### ISSUE TITLE
希望主题支持广告位

### ISSUE THREAD

**Issue by pandalabme** [halo-dev/theme-earth#108]
网站adsense审核通过，但目前只有穿插广告正常渲染，锚定广告和侧边栏广告均不能正常显示，看这个[帖子](https://bbs.halo.run/d/4163-%E5%B9%BF%E5%91%8A%E8%81%94%E7%9B%9Fadstxt%E6%96%87%E4%BB%B6%E6%80%8E%E4%B9%88%E9%83%A8%E7%BD%B2/2)上有同学反馈2.0主题没有广告位，不知道是因为这个原因导致

**Comment by ruibaby** [comment]
是不是支持[这个 issue](https://github.com/halo-dev/theme-earth/issues/103) 就可以了。

**Comment by pandalabme** [comment]
> 是不是支持[这个 issue](https://github.com/halo-dev/theme-earth/issues/103) 就可以了。

对的，目前默认主题可以支持adsense自动广告，如果解决[这个 issue](https://github.com/halo-dev/theme-earth/issues/103) 就可以支持自定义广告位功能了

**Comment by ruibaby** [comment]
感觉可以在侧边小组件加一个自定义 HTML 的组件，但这似乎需要 https://github.com/halo-dev/halo/pull/4702 的支持。

**Comment by ruibaby** [comment]
这个 Issue 先关闭了，后续关注 https://github.com/halo-dev/theme-earth/issues/103 吧。

/close
