### ISSUE TITLE
文章详情页底部翻页组件没有限制字符长度

### ISSUE THREAD

**Issue by intoyang** [halo-dev/theme-earth#12]
### 问题描述
文章详情页中，翻页组件后的标题文本超出页面长度。
![iShot_2022-11-08_19 27 16](https://user-images.githubusercontent.com/73098982/200553650-bb73767d-9686-428f-abee-9fa7322db6c3.png)
### 期望
翻页组件后的文章标题限制为 20 个字符。
### 附加信息
/kind bug

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-sigs/theme-earth/commit/220e330eb8c58714a1e3ac9cdcd413a07e33e097 中支持。
