### ISSUE TITLE
瞬间的头像显示不出来

### ISSUE THREAD

**Issue by lsh1358046425** [halo-dev/theme-earth#120]
![image](https://github.com/halo-dev/theme-earth/assets/45169615/34fcc899-a82d-4814-a7d2-215b095eabe5)

**Comment by lsh1358046425** [comment]
没有上传头像，但是首页是有这样的默认头像的，是不是不太一致？
![image](https://github.com/halo-dev/theme-earth/assets/45169615/c4259698-d632-40d6-ade3-e6eec15ad1a8)

**Comment by ruibaby** [comment]
> 没有上传头像，但是首页是有这样的默认头像的，是不是不太一致？
> 
> ![image](https://github.com/halo-dev/theme-earth/assets/45169615/c4259698-d632-40d6-ade3-e6eec15ad1a8)
> 
> 

如果这样的话，可以加上默认头像。

PR welcome～

/good-first-issue
