### ISSUE TITLE
黑夜模式似乎对英语不是很支持

### ISSUE THREAD

**Issue by LikeGiver** [halo-dev/theme-earth#122]
黑夜模式下长段英文会导致字体变成灰色，很难看清

**Comment by ruibaby** [comment]
是这里吗？

<img width="1103" alt="图片" src="https://github.com/halo-dev/theme-earth/assets/21301288/74858277-6928-4f81-8e4a-c92012042ffa">

**Comment by LikeGiver** [comment]
emmm,我的描述可能有问题，准确说是中英文都会出现，我找不到英文的示例了，中文的我找到一个
![2023-11-26 14-40-22 的屏幕截图](https://github.com/halo-dev/theme-earth/assets/42694182/94a7df21-a956-40f3-a1c3-c3939778705a)
对应的源码是这样写的：
![2023-11-26 14-41-45 的屏幕截图](https://github.com/halo-dev/theme-earth/assets/42694182/e4522c24-a0a8-47a8-84a1-e25880d72009)

**Comment by LikeGiver** [comment]
@ruibaby 
ok,我手动设置了确实可以了，感谢！
