### ISSUE TITLE
默认主题左上角logo处不支持文字

### ISSUE THREAD

**Issue by xus66666** [halo-dev/theme-earth#134]
### Describe this feature

默认主题左上角logo处不支持文字
采用图片的方式会导致黑夜模式下文字不反色,

**Comment by ruibaby** [comment]
> 默认主题左上角logo处不支持文字

支持，但是未设置 Logo 的时候才显示文字，可以考虑在主题设置中提供是否使用文字 Logo 的选项。

**Comment by xus66666** [comment]
不支持图标和文字,这个会给优化吗?


| |
xx
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | Ryan ***@***.***> |
| 发送日期 | 2024年01月31日 22:08 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [halo-dev/theme-earth] 默认主题左上角logo处不支持文字 (Issue #134) |

默认主题左上角logo处不支持文字

支持，但是未设置 Logo 的时候才显示文字，可以考虑在主题设置中提供是否使用文字 Logo 的选项。
