### ISSUE TITLE
文章详情页 favicon.ico无法显示

### ISSUE THREAD

**Issue by funtime1** [halo-dev/theme-earth#145]
你好，我在后台配置了自定义的favicon.ico：
![image](https://github.com/halo-dev/theme-earth/assets/90565575/cc7ebc15-65c8-40e2-bb10-38f17a760ba5)

但文章详情页读取的路径是https://blog.dwgg.cc:8443/favicon.ico，所以无法正确显示favicon.ico，但首页是可以正常加载的。
![image](https://github.com/halo-dev/theme-earth/assets/90565575/78099a10-9723-417f-b22e-2551061a6ee5)

复现地址：
https://blog.dwgg.cc:8443/2024/03/10/1710066214869

**Comment by funtime1** [comment]
用的是最新版的主题：1.8.0

**Comment by ruibaby** [comment]
你在内容页面注入的代码破坏了 html 的结构，导致 favicon 的标签渲染到了 body 标签里面，所以不生效。

<img width="1196" alt="image" src="https://github.com/user-attachments/assets/1b782fce-314c-4c44-9d0c-7de15caa7e82">
<img width="947" alt="image" src="https://github.com/user-attachments/assets/d75b412c-0243-4531-beef-c4dc31c0a8d5">

建议把这一块代码放在页脚注入。
