### ISSUE TITLE
导航栏登陆图标样式失效

### ISSUE THREAD

**Issue by NotPeppa** [halo-dev/theme-earth#150]
版本：1.8.0

![截屏2024-05-21 12 05 57](https://github.com/halo-dev/theme-earth/assets/144322506/996c15b2-6e54-492b-8eb5-f1bc1a39a9b1)

**Comment by NotPeppa** [comment]
验证后发现不是代码问题，我从1.7.1升级到1.8.0后，画面html的代码仍然是1.7.1的版本，同名上传也没有更新代码，修改主题唯一标识后代码为最新代码，没有上面提到的样式问题。根本原因暂时不清楚

**Comment by chenkuicn** [comment]
希望后续可以隐藏登录图标

**Comment by ruibaby** [comment]
应该与缓存有关，建议检查方向代理的缓存策略。
