### ISSUE TITLE
主题安装后404，网站无法访问但后台页面正常访问

### ISSUE THREAD

**Issue by YusCoding** [halo-dev/theme-earth#152]
如题
**halo版本:2.16**
**earth版本1.8**
通过compose安装
earth主题时会404无法打开首页，主题预览时会404，甚至是输入文章路径也404

- 尝试过在启用earth主题时卸载earth主题，首页可以显示虽然没主题但是能够正常访问

- 尝试过切换到别的主题，可以正常访问。

综上，我认为earth主题可能是存在问题。当然了我情况特殊，因为是刚从一个服务器迁移到另一个服务器后出现的这种情况不知道是否具有独特性.
下面贴出宝塔网站日志及后台报错内容：
宝塔网站日志内容：
xxxxxxxxx - - [04/Jun/2024:21:31:11 +0800] ＂GET /?preview-theme=theme-earth HTTP/2.0＂ 404 0 ＂https://xxx.com/console/theme＂ ＂Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36＂
docker服务日志内容(由于字符过多没法直接贴上来，放在附件里)：
[docker日志.txt](https://github.com/user-attachments/files/15552330/docker.txt)

**Comment by YusCoding** [comment]
看了下咱们的演示站点似乎没这个问题版本都是一样的，如果需要的话我可以提供我服务器地址和账号

**Comment by JohnNiang** [comment]
从日志看，似乎是菜单配置有问题。建议检查一下 Earth 主题中菜单相关的配置。

**Comment by YusCoding** [comment]
> 从日志看，似乎是菜单配置有问题。建议检查一下 Earth 主题中菜单相关的配置。

好的，多谢回复。我就且先关闭了这个issue了
