### ISSUE TITLE
代码块显示优化建议

### ISSUE THREAD

**Issue by Markkkkk** [halo-dev/theme-earth#155]
### 这种代码块首行为什么顶格显示，感觉视觉上不美观。
<img width="1099" alt="企业微信截图_da54979f-59cf-4c6d-b788-a0d5a258ec47" src="https://github.com/user-attachments/assets/a1b119a4-9bef-4889-a9b2-94d97e1a8b2c">

上图出处为[我的站点文章](https://www.mlgg.cc/archives/rocketmqji-qun----2m-2a-async)供参考

**Comment by ruibaby** [comment]
主题没有提供代码快高亮解析，你需要安装插件，https://www.halo.run/store/apps?keyword=%E4%BB%A3%E7%A0%81
