### ISSUE TITLE
主题配色切换，logo图片切换代码html在哪修改，有知道的大佬麻烦告知小弟一声

### ISSUE THREAD

**Issue by zxalive** [halo-dev/theme-earth#157]
<img width="641" alt="image" src="https://github.com/user-attachments/assets/c63f835e-697b-418e-9974-5b7da9c4ffd9">
<img width="534" alt="image" src="https://github.com/user-attachments/assets/dbb0d209-df00-4641-8623-519c04912641">

**Comment by zx9588** [comment]
<img width="1009" alt="image" src="https://github.com/user-attachments/assets/7989178a-b18d-4c8f-94ba-c28c74e93880">
位置找到了，怎么切，有大佬知道的告诉我一声

**Comment by zx9588** [comment]
![image](https://github.com/user-attachments/assets/f55f719e-52f8-419e-b0af-9662eb6b64df)
![image](https://github.com/user-attachments/assets/869c3a83-2c7e-410d-982a-21f0c0049bba)
改了这2个地方，还是不行，大佬指点一下

**Comment by ruibaby** [comment]
请确保已经编译，以及检查缓存。

**Comment by zx9588** [comment]
> 需要确保已经编译，以及检查缓存。

感谢回复，清了缓存还是不行，控制台都没有打印，这个方法都不走，就很纳闷
![](https://zxalive.com/upload/image-cbrn.png)

**Comment by zx9588** [comment]
> 需要确保已经编译，以及检查缓存。

我感觉是我代码写的不对，我不懂前端，这是我的修改记录：
https://zxalive.com/archives/halo-theme-earth-switch-logo-according-to-colorScheme

**Comment by zx9588** [comment]
修改了main.ts，main.life.js怎么才能刷新
<img width="1162" alt="image" src="https://github.com/user-attachments/assets/afaeea90-caca-4cc5-b716-29bd57bd3666">

**Comment by JohnNiang** [comment]
Hi @zx9588 ，看来你还是没有真正理解 https://github.com/halo-dev/theme-earth/issues/157#issuecomment-2303617375 提到的`编译`是什么意思。

关于如何构建请参考：<https://github.com/halo-dev/theme-earth#%E6%9E%84%E5%BB%BA>。

/kind support

**Comment by zx9588** [comment]
> Hi @zx9588 ，看来你还是没有真正理解 [#157 (comment)](https://github.com/halo-dev/theme-earth/issues/157#issuecomment-2303617375) 提到的`编译`是什么意思。
> 
> 关于如何构建请参考：https://github.com/halo-dev/theme-earth#%E6%9E%84%E5%BB%BA。
> 
> /kind support

哦哦 漏了编译了 我一直不知道前端代码怎么打包到那个dist目录 解决了我一个大难题 感谢
