### ISSUE TITLE
首页标题颜色异常

### ISSUE THREAD

**Issue by QYG2297248353** [halo-dev/theme-earth#166]
升级前正常，升级后异常

自动/亮色 主题下 黑底 黑字，很奇怪，如果是适配主题，那么那个 暗色大地球 也应该换掉吧。

![image](https://github.com/user-attachments/assets/cc97f757-757e-4b4d-8524-e61fd55963f5)

![image](https://github.com/user-attachments/assets/f8da4dcb-3853-408d-b580-d472e5b40c97)

![image](https://github.com/user-attachments/assets/394b9b25-d1f9-41f9-bc79-dbd01b7bd7f5)

**Comment by QYG2297248353** [comment]
> > 如果是适配主题，那么那个 暗色大地球 也应该换掉吧。
> 
> 没懂。


我还以为 是为了适配 主题：暗色 亮色 系统主题 导致的颜色修改
但是颜色咋更换，背景的地球都是偏暗色，我就以为地球会变成日出状态，适配白色字体

**Comment by ruibaby** [comment]
...

**Comment by QYG2297248353** [comment]
讲真的，地球做成动态的，那将是一大手笔

自动主题配上，看似旋转的地球

每次打开页面都是新的地球状态
