### ISSUE TITLE
代码块边距异常

### ISSUE THREAD

**Issue by DaqiHu** [halo-dev/theme-earth#170]
![image](https://github.com/user-attachments/assets/83e52589-dabe-46f1-a9ce-76c5882c8cf0)

Halo 版本 2.16.4
Earth 版本 1.9.1
Earth 风格样式：Github风格

**Comment by ruibaby** [comment]
需要安装代码高亮插件：https://www.halo.run/store/apps?keyword=%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE
