### ISSUE TITLE
一行三列布局，最后一行只有一篇文章

### ISSUE THREAD

**Issue by FunnyWii** [halo-dev/theme-earth#181]
![Screenshot from 2024-09-06 13-59-41](https://github.com/user-attachments/assets/f37dd68c-30ae-45ba-9f99-8148534f4912)

是因为不管什么布局，每页显示的文章数量是固定的吗？如果是可以调整为6的倍数吗，这样最后一行只有一篇文章，强迫症看起来有点难受呀

**Comment by ruibaby** [comment]
需要自行在文章设置中设置显示条数，主题不能控制文章显示条数。

https://docs.halo.run/user-guide/settings#文章设置

**Comment by FunnyWii** [comment]
明白了
自己也改过这个，纯粹是忘了还有这么个设置...
