### ISSUE TITLE
侧边栏小部件不显示 求处理办法

### ISSUE THREAD

**Issue by RamboGuoGuo** [halo-dev/theme-earth#185]
主题设置显示了小部件，但是前端还是没有显示侧边栏小部件，求处理办法
![Uploading QQ20240921-110631.png…]()

**Comment by ruibaby** [comment]
没有复现这个问题，你提供的图片似乎无法显示，由于这个 issue 已经过去太久，所以我将暂时关闭，如果你后续仍然能够稳定复现这个问题，可以重新提交 issue。

/close
