### ISSUE TITLE
博客标题展示优化

### ISSUE THREAD

**Issue by WAGFS** [halo-dev/theme-earth#186]
作者你好，在使用官方默认主题后遇到了一些小的体验上的问题，希望对后续版本的体验优化有所帮助：
1.博客的标题重复，后台没有办法关闭。（有些时候只想要背景图上的大标题展示）希望后续可以在后台增加一个开关，当开关打开时，下方文章中的标题不展示，直接展示正文。
![image](https://github.com/user-attachments/assets/128fb65e-15e2-48ac-a79b-0071b72b8b11)
2.上方H1标题建议增加模糊底色，增强对比度，目前标题字体颜色与背景图相近时，导致其可读性受到影响。
![image](https://github.com/user-attachments/assets/abb2e7db-785d-4fd3-9959-7e77fb13656d)

**Comment by ruibaby** [comment]
/kind bug
/good-first-issue

可以考虑在文章设置中添加一个选项，用于关闭文章封面图中的标题或者正文标题的显示。

**Comment by mufengyian** [comment]
![Image](https://github.com/user-attachments/assets/595f8d99-bfcb-4093-a0ac-e825e89cad98)
有标题被文章卡片挡住的情况
