### ISSUE TITLE
页脚备案号显示策略问题

### ISSUE THREAD

**Issue by Lin-321** [halo-dev/theme-earth#194]
在外观-主题-备案设置，只输入ICP备案号GA备案号留空无法显示，必须输入GA备案号的内容。
最好可以改成Nexus 知识库主题类似的两个备案号可选输入。

**Comment by JohnNiang** [comment]
Fixed by <https://github.com/halo-dev/theme-earth/pull/196>.

/kind bug
/assign @Anyexyz 
/close
