### ISSUE TITLE
如何实现全英文

### ISSUE THREAD

**Issue by xuan-lab** [halo-dev/theme-earth#198]

**Comment by JohnNiang** [comment]
这个需要在主题端适配一下多语言才行。

#### 参考

- https://github.com/halo-dev/rfcs/tree/main/theme#%E4%B8%BB%E9%A2%98%E5%9B%BD%E9%99%85%E5%8C%96

**Comment by xuan-lab** [comment]
好的，感谢

**Comment by JohnNiang** [comment]
Hi @xuan-lab ，建议先不管这个 Issue，等当前主题适配好多语言后，再关闭。所以我将重新打开当前 Issue。

/reopen
/kind feature

**Comment by xuan-lab** [comment]
hi，@JohnNiang 
能否发布你们的implementation plan，看看能不能参与其中，感谢。

**Comment by JohnNiang** [comment]
@xuan-lab 或许我们可以先打个样，这样可以作为一个参考，参与起来会更轻松些。
