### ISSUE TITLE
小部件的项删除后保存再次刷新还是会出现

### ISSUE THREAD

**Issue by TnZzZHlp** [halo-dev/theme-earth#20]
![图片](https://user-images.githubusercontent.com/98214647/205003185-05758d6d-5b42-4f85-b6be-1a11607f5bb8.png)

**Comment by JohnNiang** [comment]
当前 issue 建议转移到 <https://github.com/halo-dev/halo/issues>。其他主题或者插件都可能会有类似的配置，都会出现类似的问题。
