### ISSUE TITLE
选不到二级分类！在移动端浏览器

### ISSUE THREAD

**Issue by ahong18s** [halo-dev/theme-earth#201]
在移动端浏览器里，点击“一级分类”、“右侧小箭头”时，会显示“二级分类”的小弹窗、且直接跳转了“一级分类”的页面，导致无法选择二级分类。

表现：

1. 点击一级分类，出现二级分类小弹窗，显示了二级分类的列表；
2. 此时，已经跳转了“一级分类”的页面，小弹窗消失。

正确的结果：

1. 保留点击“一级分类“的功能，支持选择“二级分类”。

**Comment by ruibaby** [comment]
这是因为当前的分类 dropdown 依赖鼠标悬浮，而移动端没有这个过程，我将重构这里的分类选择，支持通过点击下拉图标展开 dropdown。

/assign
