### ISSUE TITLE
404 页面返回按钮 的默认链接 问题

### ISSUE THREAD

**Issue by szkane** [halo-dev/theme-earth#204]
**Bug：404 页面返回按钮 的默认链接 问题**

用了 1panel 的docker 安装的 halo，在某些主题和官方默认的404页面的返回首页难的链接 halo站点默认根目录是写死的：  loclhost:port  

![Image](https://github.com/user-attachments/assets/74966ad6-93de-413e-b888-c89b5baaaa21)

**Comment by ruibaby** [comment]
https://www.halo.run/archives/halo-1panel-faq#%E6%AD%A3%E7%A1%AE%E8%AE%BE%E7%BD%AE%E5%A4%96%E9%83%A8%E8%AE%BF%E9%97%AE%E5%9C%B0%E5%9D%80

**Comment by szkane** [comment]
已解决
