### ISSUE TITLE
代码无法高亮

### ISSUE THREAD

**Issue by youngledo** [halo-dev/theme-earth#225]
![Image](https://github.com/user-attachments/assets/bdaa2eb3-62cb-4d29-a6a2-e5043df2fb69)

安装了高亮插件并启用，也是如此。
![Image](https://github.com/user-attachments/assets/4456f7e4-683c-4c94-9367-3458a1ee4f65)

安装的编辑器都能正常高亮：
![Image](https://github.com/user-attachments/assets/be57a998-9ebb-454d-80b0-9ec9db543d04)

**Comment by ruibaby** [comment]
你当前 highlight.js 插件的版本是？

**Comment by ruibaby** [comment]
建议改为 bash 试试。

![Image](https://github.com/user-attachments/assets/44208b8e-15cf-4474-9a66-02c0e504b11b)
![Image](https://github.com/user-attachments/assets/acdabb87-ef59-4e21-ad8e-2b5330f10cc4)

最新版本目前是包含了所有 highlight.js 支持的语言的，我也不清楚为什么 shell 无法正常解析。

**Comment by youngledo** [comment]
试过没什么变化。切换编辑器也是一样的。

**Comment by ruibaby** [comment]
仍然没有复现你的问题，建议再确定一下是否安装的最新版本，当前的版本应该是 1.3.2，https://www.halo.run/store/apps/app-sqpgf

![Image](https://github.com/user-attachments/assets/572a3337-55c2-4e5b-bc61-e1795634ea3b)
![Image](https://github.com/user-attachments/assets/50771c93-713f-4831-8724-d5aa269f8a1b)

此外，如果你确定是这个插件的问题，请在 https://github.com/halo-sigs/plugin-highlightjs 提交 issue，此主题没有对代码块进行任何处理。

**Comment by youngledo** [comment]
这就很诡异了，我直接用Docker运行启动，就装了个高亮插件，也是如此：
```shell
docker run -d --name halo -p 8090:8090 -v ~/.halo2:/root/.halo2 halohub/halo:2.20
```
