### ISSUE TITLE
锚点链接定位错误

### ISSUE THREAD

**Issue by VoidYun** [halo-dev/theme-earth#227]
#### What type of issue is this?
/kind bug

#### System information:
已激活主题: [Earth 1.12.2](https://github.com/halo-dev/theme-earth)

#### What happened?
在访问如 https://example.com/archives/post#section 的时候，由于固定导航栏导致部分内容被遮挡

#### What did you expect to happen?
在访问如 https://example.com/archives/post#section 的时候进行偏移

#### How can we reproduce it (as minimally and precisely as possible)?
在浏览器地址栏中输入锚点链接，观察定位情况

#### Anything else we need to know?
在分享文章部分内容或者其他文章引用这部分内容的时候，锚点链接非常重要

**Comment by SkyzcYou** [comment]
测试了一下，在右侧的目录中点击目录项的时候能够正常偏移。

**Comment by VoidYun** [comment]
> 测试了一下，在右侧的目录中点击目录项的时候能够正常偏移。
> 
> 但是通过浏览器中输入锚点链接的时候不能正常偏移，会导致内容被导航栏遮挡。

是的，Tocbot生成的目录是没有问题的，主要是分享给别人带有#的链接，还有文章引用了带#的链接，这样跳转是会被遮挡的

**Comment by SkyzcYou** [comment]
> > 测试了一下，在右侧的目录中点击目录项的时候能够正常偏移。
> > 但是通过浏览器中输入锚点链接的时候不能正常偏移，会导致内容被导航栏遮挡。
> 
> 是的，Tocbot生成的目录是没有问题的，主要是分享给别人带有#的链接，还有文章引用了带#的链接，这样跳转是会被遮挡的

如果链接跳转要想实现正确偏移的话，最简单的办法可能只有更改主题布局了，不知道有没有别的办法。我研究下。

**Comment by SkyzcYou** [comment]
> > > > 测试了一下，在右侧的目录中点击目录项的时候能够正常偏移。
> > > > 但是通过浏览器中输入锚点链接的时候不能正常偏移，会导致内容被导航栏遮挡。
> > > 
> > > 
> > > 是的，Tocbot生成的目录是没有问题的，主要是分享给别人带有#的链接，还有文章引用了带#的链接，这样跳转是会被遮挡的
> > 
> > 
> > 如果链接跳转要想实现正确偏移的话，最简单的办法可能只有更改主题布局了，不知道有没有别的办法。我研究下。
> 
> 给 html 标签添加 scroll-padding-top 样式，并移除 tocbot 的 tocScrollOffset 参数。

牛，大佬一针见血。刚刚还在到处查资料如何实现 🤣(
我试了这个方法确实成功了，已提交PR
