### ISSUE TITLE
主题滚动页面产生抖动效果

### ISSUE THREAD

**Issue by XiaoMoDonnie** [halo-dev/theme-earth#27]
主题在PC端和移动端下，滚动页面的时候有抖动，经过观察，应该是页面在滚动的时候将顶部的导航区域加了css  `position:fixed` 。

**Comment by ruibaby** [comment]
我将改为 sticky 定位。

/assign

**Comment by XiaoMoDonnie** [comment]
good good!!!

**Comment by ruibaby** [comment]
/close

see https://github.com/halo-dev/theme-earth/pull/31
