### ISSUE TITLE
建议移动端加入导航功能

### ISSUE THREAD

**Issue by XiaoMoDonnie** [halo-dev/theme-earth#28]
建议移动端加入导航功能

**Comment by ruibaby** [comment]
这理论上是一个 bug，应该是在 https://github.com/halo-dev/theme-earth/commit/bac64272592d7e1bcc3c9ef6616c48b9334db1e8 提交中将展开菜单的图标弄丢了。

/kind bug

**Comment by XiaoMoDonnie** [comment]
666 妥妥的
