### ISSUE TITLE
友情链接页面的链接无法正常跳转。

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/theme-earth#35]
<img width="701" alt="image" src="https://user-images.githubusercontent.com/21301288/209791075-e9a00b31-d712-4912-8951-c9900ef0cacb.png">

原因是这个 a 标签没有绑定 href。

/kind bug
/good-first-issue

**Comment by LarryDpk** [comment]
你好，我在1.1.1版本也还是遇到了这个的问题。
Halo是2.1.0版本。
配置应该是正常的：
<img width="646" alt="image" src="https://user-images.githubusercontent.com/9039939/212291742-91812d4e-3965-478f-8028-311321d7494c.png">


主题是1.1.1版本：
<img width="704" alt="image" src="https://user-images.githubusercontent.com/9039939/212291212-81f44259-86f8-487f-b8bf-a08e0a09283b.png">


但链接还是有问题：
<img width="437" alt="image" src="https://user-images.githubusercontent.com/9039939/212291335-123c4fcd-6218-42c1-8cde-e001d9fa389b.png">

**Comment by LarryDpk** [comment]
我根据PR的commit修改文件暂时fix啦~

**Comment by ruibaby** [comment]
@LarryDpk https://github.com/halo-dev/theme-earth/compare/v1.1.0...v1.1.1

1.1.1 是包含了这个修改的，不太清楚是什么原因导致模板没有更新。你的主题更新方式是？
