### ISSUE TITLE
公式无法显示

### ISSUE THREAD

**Issue by wt12318** [halo-dev/theme-earth#41]
写文章时候正常：
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/39486023/212529177-19283dc1-a6ed-4342-91d3-28b02074f754.png">
但是网页无法显示公式：
<img width="667" alt="image" src="https://user-images.githubusercontent.com/39486023/212529191-1fa05c5f-5259-40be-938d-2d8300798ab5.png">

我用的是 2.1.0 版本的 Halo

**Comment by JohnNiang** [comment]
这个是编辑器的问题，可以从[这里](https://github.com/halo-sigs/awesome-halo)下载一个 Markdown 编辑器，再试试。

/kind support
