### ISSUE TITLE
markdown的单行代码语法没有被渲染

### ISSUE THREAD

**Issue by funtime1** [halo-dev/theme-earth#42]
![图片](https://user-images.githubusercontent.com/90565575/212536217-8be4cd73-af70-4a97-bc88-6ee1531f2b87.png)

**Comment by ruibaby** [comment]
这是因为文章渲染样式就是这样的，使用了 https://tailwindcss.com/docs/typography-plugin

**Comment by funtime1** [comment]
好滴.  这种渲染格式还是第一次见,有点非主流啊.

**Comment by ruibaby** [comment]
> 好滴. 这种渲染格式还是第一次见,有点非主流啊.

确实有点，后续可以考虑再集成一种渲染方案，比如 https://github.com/sindresorhus/github-markdown-css

**Comment by duanluan** [comment]
坐等
