### ISSUE TITLE
无法高亮代码块

### ISSUE THREAD

**Issue by PandyYang** [halo-dev/theme-earth#50]
指定了语言类型，还是没有高亮。是还需要什么操作吗，我是用的默认的。

**Comment by JohnNiang** [comment]
安装插件 https://github.com/halo-sigs/plugin-highlightjs 再试试。

/kind support

**Comment by PandyYang** [comment]
> 安装插件 https://github.com/halo-sigs/plugin-highlightjs 再试试。
> 
> /kind support

感谢，成功了。
