### ISSUE TITLE
每篇文章卡片hover上去都是手型，但是只有点击图片和大标题才可跳转

### ISSUE THREAD

**Issue by jdgjxxchy** [halo-dev/theme-earth#53]
a标签应该置于卡片上，或者说这本身是设计如此？不能理解的是为什么需要在卡片上加上cursor-pointer

**Comment by ruibaby** [comment]
PR Welcome :)

/kind improvement

**Comment by JohnNiang** [comment]
Hi @jdgjxxchy ，可以直接回复 `/assign` 可认领当前 Issue。

/good-first-issue
