### ISSUE TITLE
访问隐藏文章会报Http 500 error

### ISSUE THREAD

**Issue by Uyouii** [halo-dev/theme-earth#54]
具体错误如图：
<img width="885" alt="截屏2023-02-23 18 40 56" src="https://user-images.githubusercontent.com/25459212/220884178-5903eae3-99ed-42be-8139-46b224ad8fff.png">

**Comment by JohnNiang** [comment]
目前 Halo 还没有开发隐藏文章的功能，所以访问可能会有问题。
