### ISSUE TITLE
不支持Moment插件

### ISSUE THREAD

**Issue by yangjinchangboy** [halo-dev/theme-earth#70]
建议在主题市场增加显示每个主题支持哪些插件，介绍里面也没有说支持哪些插件，安装了才知道不支持。

**Comment by ColanCN** [comment]
额，是的我也发现这个问题，我也在Telegram上询问过Ryan Wang，他确认是Halo2的默认主题是不支持Moment插件的。

**Comment by ruibaby** [comment]
> 是的，我也发现这个问题，而且我也在Telegram上询问过Ryan Wang，他说Halo2默认主题是不支持Moment插件的。

主要是因为这个主题的风格不太好提供这样的页面，不过我打算暂时使用一下之前为 https://github.com/halo-dev/halo-theme-anatole 做的布局。

**Comment by ColanCN** [comment]
> > 是的，我也发现这个问题，而且我也在Telegram上询问过Ryan Wang，他说Halo2默认主题是不支持Moment插件的。
> 
> 主要是因为这个主题的风格不太好提供这样的页面，不过我打算暂时使用一下之前为 https://github.com/halo-dev/halo-theme-anatole 做的布局。
> 
> Preview：https://ryanc.cc/moments

是的，主要还是比较喜欢默认的主题。

**Comment by lsh1358046425** [comment]
请问什么时候可以支持呢？
