### ISSUE TITLE
Support English Version

### ISSUE THREAD

**Issue by LarryDpk** [halo-dev/theme-earth#75]
Hi team, 
Can this awesome theme support **English** version? Also provide a switch **button** for the languages switching.

**Comment by JohnNiang** [comment]
It would be better if you explain which parts you want to support.

In fact, we support locale mechanism but we haven't adapt it to this theme currently. If you want learn more about i18n, please refer to <https://github.com/halo-dev/rfcs/issues/6>.

**Comment by LarryDpk** [comment]
My requirement is easier, I want the page show in English for all Title/Label. For example:
标签 --> tag,
更多--> more,
上一页、下一页 --> last page, next page

<img width="308" alt="image" src="https://user-images.githubusercontent.com/9039939/234495527-914d2de3-85d2-4a6f-86e1-aa6532afd2db.png">
to be: Posts, Categories, Comment, Read

**Comment by firstsaofan** [comment]
将来是否会支持一篇文章支持多种语言，多语言内容自己编写。然后根据用户的url或者系统默认语言显示对应的版本。虽然现在我可以写2篇博客添加对应的超链接，但是这样博客会多了同样的文章。

Will it be possible to support multiple languages for an article in the future, and write your own content in multiple languages. Then display the corresponding version based on the user's URL or system default language. Although I can now write 2 blogs with corresponding hyperlinks, this will add the same article to the 

![多语言版本](https://user-images.githubusercontent.com/52733945/236691785-813305d5-0069-420e-9c89-7c9f41d70f44.png)

**Comment by ruibaby** [comment]
> 将来是否会支持一篇文章支持多种语言，多语言内容自己编写。然后根据用户的url或者系统默认语言显示对应的版本。虽然现在我可以写2篇博客添加对应的超链接，但是这样博客会多了同样的文章。
> 
> Will it be possible to support multiple languages for an article in the future, and write your own content in multiple languages. Then display the corresponding version based on the user's URL or system default language. Although I can now write 2 blogs with corresponding hyperlinks, this will add the same article to the
> 
> ![多语言版本](https://user-images.githubusercontent.com/52733945/236691785-813305d5-0069-420e-9c89-7c9f41d70f44.png)

不再考虑实现多语言内容管理，参考：https://github.com/halo-dev/rfcs/issues/6#issuecomment-2481252386

但仍然会推进界面元素的 i18n，https://github.com/halo-dev/theme-earth/pull/214
