### ISSUE TITLE
文章目录展示区域太小了

### ISSUE THREAD

**Issue by lululu0515** [halo-dev/theme-earth#77]
文章目录展示区域太小了，对于目录层级比较多的文章，不能一目了然的看到整个文章的所有目录，需要滚动很多才能看完整个文章目录

建议把目录展示区域加长，或者是根据文章目录动态显示长度，毕竟目录就是用来快速索引，快速了解文章大纲的功能，所以其实不应该增加目录的浏览成本

**Comment by ruibaby** [comment]
cc @L-fw
