### ISSUE TITLE
搜索结果页面的连接是 localhost:8090

### ISSUE THREAD

**Issue by freehuoshan** [halo-dev/theme-earth#78]
搜索结果页面的连接是 localhost:8090

**Comment by ruibaby** [comment]
此问题与主题无关，你需要检查 external-url 是否设置正确。https://docs.halo.run/getting-started/install/docker-compose#:~:text=mysql%E3%80%81h2-,halo.external%2Durl,-%E5%A4%96%E9%83%A8%E8%AE%BF%E9%97%AE%E9%93%BE

如果已经改为正确的地址，可以尝试在 Console 仪表盘中的 **快捷访问** 刷新搜索引擎。

/close
