### ISSUE TITLE
不支持行内公式\行间公式

### ISSUE THREAD

**Issue by maicaoboy** [halo-dev/theme-earth#83]
已经引入
<link rel="stylesheet" href="https://unpkg.com/katex@0.12.0/dist/katex.min.css" />
还是不显示公式

**Comment by ruibaby** [comment]
KaTeX 插件的首个版本已经发布，可以将 Halo 升级到 2.7，然后安装此插件进行体验。

- https://github.com/halo-sigs/plugin-katex/releases/tag/v1.0.0
- https://halo.run/store/apps/app-ISCsX

/close
