### ISSUE TITLE
bug反馈：文章页面中，目录被某些元素遮挡

### ISSUE THREAD

**Issue by Litbay** [halo-dev/theme-earth#84]
## 版本信息
halo2.6，earth1.4.0
## 问题描述
如图所示，在文章页面，目录悬浮后会被站点资料的logo（默认使用站点logo）、分类目录的部分元素遮挡
<br/>
![图片1](https://imghost.litbay.cn/issue1.png)
![图片2](https://imghost.litbay.cn/issue2.png)
![图片3](https://imghost.litbay.cn/issue3.png)

**Comment by sicode** [comment]
按照最新的代码，手动修复，问题依旧

**Comment by JohnNiang** [comment]
> 按照最新的代码，手动修复，问题依旧

因为 Halo 默认情况下是缓存了模板文件的，所以直接修改模板文件是不会生效，需要上传主题包或者重启服务器。
