### ISSUE TITLE
从风格二切回风格一后，底部居中功能失效

### ISSUE THREAD

**Issue by LeCadeau** [halo-dev/theme-earth#94]
![image](https://github.com/halo-dev/theme-earth/assets/94001156/71627ad8-fe00-46bb-ab00-1c22ce32a333)

**Comment by JohnNiang** [comment]
Hi @LeCadeau ，建议提供一下当前主题的版本。如果不是最新版，建议更新至最新版后再试试。

/triage needs-information

**Comment by LeCadeau** [comment]
> Hi @LeCadeau ，建议提供一下当前主题的版本。如果不是最新版，建议更新至最新版后再试试。
> 
> /triage needs-information

![image](https://github.com/halo-dev/theme-earth/assets/94001156/b5b812c4-1024-4b4c-8b9f-cc840206c022)
V1.4.0
