### ISSUE TITLE
文章侧边自动生成的目录，与分类/标签/站点资料文字重合（V1.4.0）

### ISSUE THREAD

**Issue by LeCadeau** [halo-dev/theme-earth#95]
![image](https://github.com/halo-dev/theme-earth/assets/94001156/32bfbca1-bfe9-4584-a46a-823269e9f922)

**Comment by ruibaby** [comment]
这个问题已经在 https://github.com/halo-dev/theme-earth/pull/85 中修复，需要等待发布一个新的版本。

/triage duplicate
